/**
 * Single place for dataset file locations (repo-root–relative resolved to absolute).
 * Raw inputs: `dataset/`. Generated artifacts consumed by Next: `src/data/`.
 */

import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
export const REPO_ROOT = resolve(__dirname, "..");

export const DATASET_DIR = resolve(REPO_ROOT, "dataset");

/** Utah Startup Map — hackathon CSV export */
export const MAP_COMPANIES_CSV = resolve(
  DATASET_DIR,
  "Map Data for Builder Day  - Sheet1.csv",
);

/** Founder's Navigator — state resources workbook (future / current pipeline) */
export const RESOURCES_WORKBOOK = resolve(
  DATASET_DIR,
  "Resources List - Builder Day.xlsx",
);

/** Generated by `npm run data` — do not edit by hand */
export const GENERATED_COMPANIES_JSON = resolve(
  REPO_ROOT,
  "src",
  "data",
  "companies.json",
);

/** Cache to avoid re-geocoding everything and hitting rate limits */
export const GEOCODE_CACHE_JSON = resolve(
  DATASET_DIR,
  "geocode-cache.json"
);
